import * as mainShapesAnim from './js/main_shapes_anim'
import * as svgLogoResizw from './js/svg_logor_resize'
import * as mainBtnAnimation from './js/main_btn_animation'
import * as bgCircleAnim from './js/bg_circle_anim'
import * as h1Anim from './js/h1_anim'
import * as ballCompositionAnim from './js/ball_composition_anim'