import * as mainShapesAnim from './js/main_shapes_anim'
import * as svgLogoResize from './js/svg_logo_resize'
import * as mainBtnAnim from './js/main_btn_anim'
import * as bgCircleAnim from './js/bg_circle_anim'
import * as h1Anim from './js/h1_anim'
import * as ballCompositionAnim from './js/ball_composition_anim'
import * as DrawSvg from './js/draw_unicorn_anim'